version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
     - ./data:/data
     - ./logs:/logs
     - ./plugins:/plugins
     - ./import:/var/lib/neo4j/import

    environment:
      - NEO4J_AUTH=neo4j/password

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - neo4j
